services:
  - type: web
    name: rasternorm-backend
    runtime: python
    buildCommand: pip install --prefer-binary -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
